sudo: true
language: node_js
node_js:
  - "8.11.1"

before_cache:
  - rm -f $HOME/.meteor/log/*.log

cache:
  directories:
    - $HOME/package/.npm
    - $HOME/testing/.meteor
    - $HOME/testing/node_modules

before_install:
  - curl https://install.meteor.com/?release=1.7.0.4 | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
  - export PROJECT_ROOT=$(pwd)
  - npm install -g codacy-coverage

install:
  - cd $PROJECT_ROOT/testing
  - meteor npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - cd $PROJECT_ROOT/testing
  - ./test.sh
  - cat .coverage/lcov.info | codacy-coverage || true # ignore codacy error
