sudo: true
dist: trusty

# addons:
#  apt:
#    sources:
#      - google-chrome
#    packages:
#      - google-chrome-stable

language: node_js

addons:
  chrome: stable

node_js:
  - "8.11.1"

cache:
  directories:
    - $HOME/package/.npm
    - $HOME/tests/.meteor
    - $HOME/tests/node_modules

before_cache:
  - rm -f $HOME/.meteor/log/*.log

before_install:
  - export PATH="$HOME/.meteor:$PATH"
  - curl https://install.meteor.com/?release=1.6.1.1 | /bin/sh
  # Install dependencies
  - npm install -g eslint codacy-coverage

install:
  - export CURRENT_PACKAGE=$(pwd)
  - ./install.sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - cd tests-coverage
  - meteor npm run test
  - cat .coverage/lcov.info | codacy-coverage || true # ignore codacy error
