sudo: required
dist: trusty

language: node_js
node_js:
  - "8.11.1"

before_cache:
  - rm -f $HOME/.meteor/log/*.log

cache:
  directories:
    - $HOME/package/.npm
    - $HOME/tests/.meteor
    - $HOME/tests/node_modules

before_install:
  - curl https://install.meteor.com/?release=1.6.1.1 | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
  - export PROJECT_ROOT=$(pwd)
  - npm install -g codacy-coverage

install:
  - ./install.sh

script:
  - cd $PROJECT_ROOT/tests
  - meteor npm run test
  - cat .coverage/lcov.info | codacy-coverage || true # ignore codacy error
